name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
 run:
  working-directory: ./simplebank

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - uses: actions/checkout@v3

    - name: Test
      run: make test
